# Dependency Review configuration
# Enforce high-severity policy for dependency updates in pull requests.
fail-on-severity: high
allow-licenses:
  - MIT
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - Python-2.0
  - CC0-1.0
  - 0BSD
  - Unlicense
