version: 2
updates:

  # ✅ Python (FastAPIなど)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    open-pull-requests-limit: 5

  # ✅ Rust (bot_manager など)
  - package-ecosystem: "cargo"
    directory: "/docker/vault"
    schedule:
      interval: "daily"
      time: "00:00"
    open-pull-requests-limit: 5

  # ✅ Node.js (frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
      time: "00:00"
    open-pull-requests-limit: 5
