version: "3.9"

services:
  minio:
    image: minio/minio:RELEASE.2026-01-28T22-07-57Z
    container_name: marketdata-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:17-alpine
    container_name: marketdata-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-profinaut_marketdata}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-profinaut_marketdata}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mc-init:
    image: minio/mc:RELEASE.2026-01-15T12-36-47Z
    container_name: marketdata-minio-init
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      BRONZE_BUCKET: ${BRONZE_BUCKET:-bronze-raw}
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "mc alias set local http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD &&
      mc mb --ignore-existing local/$BRONZE_BUCKET &&
      mc anonymous set private local/$BRONZE_BUCKET"
    restart: "no"

volumes:
  minio_data:
  postgres_data:
