global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: profinaut-prod



rule_files:
  - "rules/alert.rules.yml"

scrape_configs:

  # --- Prometheus 自身 ---
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # --- Profinaut Bots（FastAPI / Rust Exporter）---
  - job_name: 'profinaut-bots'
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets:
          - api.profinaut.studiokeke.com
    bearer_token_file: /etc/prometheus/tokens/profinaut-signal-token.txt
    tls_config:
      insecure_skip_verify: true

  # --- Trade Executor Bot ---
  - job_name: 'trade'
    scheme: https
    metrics_path: /metrics/trade
    static_configs:
      - targets:
          - api.profinaut.studiokeke.com
    bearer_token_file: /etc/prometheus/tokens/profinaut-trade-token.txt
    tls_config:
      insecure_skip_verify: true

  # --- Kafka Exporter（Cloudflare Tunnel経由）---
  - job_name: 'kafka'
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets:
          - kafka.profinaut.studiokeke.com
    bearer_token_file: /etc/prometheus/tokens/profinaut-metrics-token.txt
    tls_config:
      insecure_skip_verify: true

  # --- Node Exporter（システムメトリクス）---
  - job_name: 'node_exporter'
    scheme: https
    static_configs:
      - targets:
          - node.profinaut.studiokeke.com
    bearer_token_file: /etc/prometheus/tokens/profinaut-metrics-token.txt
    tls_config:
      insecure_skip_verify: true

  # --- MongoDB Exporter ---
  - job_name: 'mongodb'
    scheme: https
    static_configs:
      - targets:
          - mongo.profinaut.studiokeke.com
    bearer_token_file: /etc/prometheus/tokens/profinaut-metrics-token.txt
    tls_config:
      insecure_skip_verify: true

  # --- Vault 本体の組み込みメトリクス（/v1/sys/metrics）---
  - job_name: 'vault'
    scheme: https
    metrics_path: /v1/sys/metrics
    static_configs:
      - targets:
          - vault.profinaut.studiokeke.com
    bearer_token_file: /etc/prometheus/tokens/profinaut-vault-token.txt
    tls_config:
      insecure_skip_verify: true

  # ✅--- Vault SECRET TTL Exporter（ローカルExporter）---
  - job_name: 'vault_secret_ttl_exporter'
    metrics_path: /metrics
    static_configs:
      - targets:
          - vault-exporter:9811

  # --- システム統合 Job（すべてまとめて監視） ---
  - job_name: 'system_monitor'
    scheme: https
    static_configs:
      - targets:
          - node.profinaut.studiokeke.com
          - kafka.profinaut.studiokeke.com
          - mongo.profinaut.studiokeke.com
          - vault.profinaut.studiokeke.com
    bearer_token_file: /etc/prometheus/tokens/profinaut-metrics-token.txt
    tls_config:
      insecure_skip_verify: true
