tunnel: dc0e81d8-932a-4581-9d5e-603e60a6c8bb
credentials-file: ./dc0e81d8-932a-4581-9d5e-603e60a6c8bb.json

ingress:
  - hostname: vault.profinaut.studiokeke.com
    service: tcp://vault:8200

  - hostname: webhook.profinaut.studiokeke.com
    service: http://webhook_server:8000

  - hostname: prometheus.profinaut.studiokeke.com
    service: http://prometheus:9090

  - hostname: grafana.profinaut.studiokeke.com
    service: http://grafana:3000

  - hostname: alerts.profinaut.studiokeke.com
    service: http://alertmanager:9093

  - service: http_status:404