tunnel: dc0e81d8-932a-4581-9d5e-603e60a6c8bb
credentials-file: ./dc0e81d8-932a-4581-9d5e-603e60a6c8bb.json

ingress:
  - hostname: vault.profinaut.studiokeke.com
    service: https://vault:8200
    originRequest:
      originServerName: vault.internal        # （Vault の cert の CN/SAN に合わせる）
      caPool: /etc/cloudflared/vault_root_ca.pem


  - hostname: webhook.profinaut.studiokeke.com
    service: http://webhook_server:8000

  - hostname: prometheus.profinaut.studiokeke.com
    service: http://prometheus:9090

  - hostname: grafana.profinaut.studiokeke.com
    service: http://grafana:3000

  - hostname: alerts.profinaut.studiokeke.com
    service: http://alertmanager:9093

  - service: http_status:404