from __future__ import annotations

SCHEMA_VERSION_CORRELATION = "obs.correlation.v1"
SCHEMA_VERSION_HEALTHZ = "obs.healthz.v1"
SCHEMA_VERSION_CAPABILITIES = "obs.capabilities.v1"
SCHEMA_VERSION_LOG_EVENT = "obs.log_event.v1"

HEADER_REQUEST_ID = "X-Request-ID"
HEADER_TRACE_ID = "X-Trace-ID"
HEADER_RUN_ID = "X-Run-ID"
HEADER_EVENT_ID = "X-Event-ID"
HEADER_SCHEMA_VERSION = "X-Schema-Version"
HEADER_INSTANCE_ID = "X-Instance-ID"
HEADER_OP = "X-Op"
HEADER_OBS_SCHEMA = "X-Obs-Schema"
HEADER_TRACEPARENT = "traceparent"

SERVICE_NAME_ENV = "PROFINAUT_SERVICE_NAME"
SERVICE_VERSION_ENV = "PROFINAUT_SERVICE_VERSION"
BUILD_SHA_ENV = "PROFINAUT_GIT_SHA"
INSTANCE_ID_ENV = "PROFINAUT_INSTANCE_ID"
