from __future__ import annotations

SCHEMA_VERSION_CORRELATION = "obs.correlation.v1"
SCHEMA_VERSION_HEALTHZ = "obs.healthz.v1"
SCHEMA_VERSION_CAPABILITIES = "obs.capabilities.v1"

HEADER_RUN_ID = "x-run-id"
HEADER_INSTANCE_ID = "x-instance-id"
HEADER_OP = "x-op"
HEADER_OBS_SCHEMA = "x-obs-schema"
HEADER_TRACEPARENT = "traceparent"

SERVICE_NAME_ENV = "PROFINAUT_SERVICE_NAME"
SERVICE_VERSION_ENV = "PROFINAUT_SERVICE_VERSION"
BUILD_SHA_ENV = "PROFINAUT_GIT_SHA"
INSTANCE_ID_ENV = "PROFINAUT_INSTANCE_ID"
