# .github/workflows/deploy.yml
name: Profinaut Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VAULT_ADDR: https://vault.profinaut.studiokeke.com:8200

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load .env.generated
        run: |
          if [ -f docker/vault/.env.generated ]; then
            echo "🔐 Loading .env.generated"
            export $(grep -v '^#' docker/vault/.env.generated | xargs)
          else
            echo "⚠️ .env.generated not found. AppRole login may fail."
          fi

      - name: Run deployment script (example)
        run: |
          echo "Using Role ID: $BOT_MANAGER_ROLE_ID"
          echo "Deploying bot_manager..."
