name: Deploy to Profinaut Host

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 1'  # 毎週月曜 00:00 UTC = JST 09:00

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USER }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          port: 22
          script: |
            cd ~/profinaut/docker
            echo "📥 Pulling latest changes..."
            git pull origin main

            echo "🐳 Pulling Docker images..."
            docker compose pull

            echo "🚀 Restarting services..."
            docker compose up -d

            echo "✅ Deployed at $(date)"
