name: 🔄 Renew Vault Secret ID

on:
  schedule:
    - cron: '0 0 * * 1'   # 毎週月曜 00:00 UTC (= JST 09:00)
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  renew-secret:
    runs-on: ubuntu-latest
    env:
      VAULT_ADDR: https://vault.profinaut.studiokeke.com:8200
      VAULT_CERT: /tmp/origin_ca.pem
      PROFINAUT_ADMIN_ROLE_ID: ${{ secrets.PROFINAUT_ADMIN_ROLE_ID }}
      PROFINAUT_ADMIN_SECRET_ID: ${{ secrets.PROFINAUT_ADMIN_SECRET_ID }}
      CF_ACCESS_CLIENT_ID: ${{ secrets.VAULT_CF_ACCESS_CLIENT_ID }}
      CF_ACCESS_CLIENT_SECRET: ${{ secrets.VAULT_CF_ACCESS_CLIENT_SECRET }}
      GH_TOKEN: ${{ secrets.GH_PAT }}
      SECRET_ROTATION_MANIFEST: docker/vault/secret_rotation.yml

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🔧 Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          echo "${{ secrets.VAULT_ORIGIN_CA_PEM }}" > "$VAULT_CERT"
          curl -sSL https://github.com/cli/cli/releases/download/v2.62.0/gh_2.62.0_linux_amd64.tar.gz \
            | tar xz
          sudo cp gh_2.62.0_linux_amd64/bin/gh /usr/local/bin/gh
          gh --version

      - name: 🧩 Prepare rotation manifest (if missing)
        run: |
          if [ ! -f "$SECRET_ROTATION_MANIFEST" ]; then
            mkdir -p "$(dirname "$SECRET_ROTATION_MANIFEST")"
            cat > "$SECRET_ROTATION_MANIFEST" <<'YAML'
# role名 → GitHub Secret名の対応
roles:
  - role: bot-manager
    secrets:
      - name: BOT_MANAGER_SECRET_ID
  - role: signal-engine
    secrets:
      - name: SIGNAL_ENGINE_SECRET_ID
  - role: trade-executor
    secrets:
      - name: TRADE_EXECUTOR_SECRET_ID
              YAML
              fi

  - name: 🔁 Renew SECRET_ID and Update GitHub Secret
    run: bash docker/vault/scripts/renew_secret_id_and_update_github.sh
