name: 🔄 Renew Vault Secret ID

on:
  schedule:
    - cron: '0 0 * * 1'  # 毎週月曜 00:00 UTC = 9:00 JST
  workflow_dispatch:

jobs:
  renew-secret:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🔁 Renew SECRET_ID and Update GitHub Secret
        run: bash docker/vault/scripts/renew_secret_id_and_update_github.sh
        env:
          VAULT_ADDR: https://vault.profinaut.studiokeke.com:8200
          PROFINAUT_ADMIN_ROLE_ID: ${{ secrets.PROFINAUT_ADMIN_ROLE_ID }}
          PROFINAUT_ADMIN_SECRET_ID: ${{ secrets.PROFINAUT_ADMIN_SECRET_ID }}
          GH_TOKEN: ${{ secrets.GH_PAT }}  # GitHub CLI Token