name: 🩺 vault_diagnostics

on:
  workflow_dispatch:

jobs:
  diagnose_vault:
    runs-on: ubuntu-latest

    env:
      VAULT_URL: https://vault.profinaut.studiokeke.com:8200
      CF_ACCESS_CLIENT_ID: ${{ secrets.VAULT_CF_ACCESS_CLIENT_ID }}
      CF_ACCESS_CLIENT_SECRET: ${{ secrets.VAULT_CF_ACCESS_CLIENT_SECRET }}

    steps:
      - name: step_1_checkout_repository
        uses: actions/checkout@v4

      - name: step_2_dns_lookup
        run: |
          echo "🔍 DNS lookup..."
          nslookup vault.profinaut.studiokeke.com || true

      - name: step_3_tcp_port_test_8200
        run: |
          echo "🔍 TCP port 8200 接続テスト..."
          timeout 10 bash -c "cat < /dev/null > /dev/tcp/vault.profinaut.studiokeke.com/8200" && echo "✅ 接続成功" || echo "❌ 接続失敗"

      - name: step_4_tls_handshake_without_header
        run: |
          echo "🔍 curl (TLSのみ・ヘッダーなし)..."
          curl -vk $VAULT_URL || true

      - name: step_5_tls_with_cf_access_headers
        run: |
          echo "🔍 curl (CF Accessヘッダー付き)..."
          curl -vk $VAULT_URL/v1/sys/health \
            -H "CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID" \
            -H "CF-Access-Client-Secret: $CF_ACCESS_CLIENT_SECRET" || true

      - name: step_6_tls_with_cf_headers_and_origin_ca
        run: |
          echo "${{ secrets.VAULT_ORIGIN_CA_PEM }}" > /tmp/origin_ca.pem
          echo "🔍 curl (CFヘッダー + origin_ca証明書)..."
          curl -vk $VAULT_URL/v1/sys/health \
            -H "CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID" \
            -H "CF-Access-Client-Secret: $CF_ACCESS_CLIENT_SECRET" \
            --cacert /tmp/origin_ca.pem || true