name: 🧪 Vault_Tunnel_Diagnostic_Step_By_Step

on:
  workflow_dispatch:

jobs:
  diagnose_vault:
    runs-on: ubuntu-latest

    env:
      VAULT_ADDR: https://vault.profinaut.studiokeke.com:8200
      CF_ACCESS_CLIENT_ID: ${{ secrets.VAULT_CF_ACCESS_CLIENT_ID }}
      CF_ACCESS_CLIENT_SECRET: ${{ secrets.VAULT_CF_ACCESS_CLIENT_SECRET }}

    steps:
      - name: 📁 Step_1_Checkout
        uses: actions/checkout@v4

      - name: 🧰 Step_2_Install_Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl dnsutils netcat

      - name: 🌍 Step_3_DNS_Resolution
        run: |
          echo "🔍 DNS resolution for Vault:"
          dig +short vault.profinaut.studiokeke.com

      - name: 🔌 Step_4_TCP_Connection_Test_443
        run: |
          echo "🔌 Testing TCP connection to port 443..."
          nc -zv vault.profinaut.studiokeke.com 443 || echo "❌ TCP connection to 443 failed"

      - name: 🔌 Step_5_TCP_Connection_Test_8200
        run: |
          echo "🔌 Testing TCP connection to Vault port 8200..."
          nc -zv vault.profinaut.studiokeke.com 8200 || echo "❌ TCP connection to 8200 failed"

      - name: 📄 Step_6_Save_Root_CA
        run: |
          echo "📄 Saving VAULT_ROOT_CA_PEM to /tmp/root_ca.pem..."
          printf "%b\n" "${{ secrets.VAULT_ROOT_CA_PEM }}" > /tmp/root_ca.pem
          ls -l /tmp/root_ca.pem

      - name: 🔐 Step_7_TLS_Handshake_Test
        run: |
          echo "🔐 Performing TLS handshake with root CA..."
          curl -vk https://vault.profinaut.studiokeke.com:8200 \
            --cacert /tmp/root_ca.pem || echo "❌ TLS handshake failed"

      - name: 🔐 Step_8_Without_CA_Test (Expected Fail)
        run: |
          echo "⚠️ Checking Vault health without CA cert (may fail)..."
          curl -vk "$VAULT_ADDR/v1/sys/health" || echo "❌ Expected failure due to missing CA"

      - name: 🌐 Step_9_Health_With_CA
        run: |
          echo "🌐 Checking Vault health with CA cert only..."
          curl -vk "$VAULT_ADDR/v1/sys/health" \
            --cacert /tmp/root_ca.pem || echo "❌ Failed with CA"

      - name: 🔐 Step_10_CF_Access_With_CA
        run: |
          echo "🔐 Checking Vault health with CF Access and CA cert..."
          curl -vk "$VAULT_ADDR/v1/sys/health" \
            -H "CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID" \
            -H "CF-Access-Client-Secret: $CF_ACCESS_CLIENT_SECRET" \
            --cacert /tmp/root_ca.pem || echo "❌ CF Access with CA failed"
