name: Vault Cloudflare Tunnel Diagnostics

on:
  workflow_dispatch:

jobs:
  diagnose-vault:
    runs-on: ubuntu-latest

    env:
      VAULT_ADDR: https://vault.profinaut.studiokeke.com:8200
      CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
      CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
      VAULT_CERT: /tmp/origin_ca.pem

    steps:
      - name: Step 1: Checkout
        uses: actions/checkout@v4

      - name: Step 2: Install curl and unzip
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip

      - name: Step 3: Save cert file
        run: |
          mkdir -p /tmp
          echo "${{ secrets.VAULT_ROOT_CA_PEM }}" > /tmp/origin_ca.pem

      - name: Step 4: Vault health check
        run: |
          echo "Vault health check..."
          curl --fail -vk "$VAULT_ADDR/v1/sys/health" \
            -H "CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID" \
            -H "CF-Access-Client-Secret: $CF_ACCESS_CLIENT_SECRET" \
            --cacert "$VAULT_CERT"

      - name: Step 5: Vault test request
        run: |
          echo "Send test secret..."
          PAYLOAD='{
            "data": {
              "diagnostic": "Vaultアクセス成功"
            }
          }'
          curl --fail -X POST "$VAULT_ADDR/v1/secret/data/diagnostic" \
            -H "CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID" \
            -H "CF-Access-Client-Secret: $CF_ACCESS_CLIENT_SECRET" \
            -H "Content-Type: application/json" \
            --data "$PAYLOAD" \
            --cacert "$VAULT_CERT"