name: Vault Init (Service Token)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  init-vault:
    name: 🔐 Vault Init + Secrets Sync
    runs-on: ubuntu-latest

    env:
      VAULT_ADDR: https://vault.profinaut.studiokeke.com:8200
      VAULT_CERT: /tmp/origin_ca.pem
      ENV_PATH: ${{ github.workspace }}/docker/.env
      CF_ACCESS_CLIENT_ID: ${{ secrets.VAULT_CF_ACCESS_CLIENT_ID }}
      CF_ACCESS_CLIENT_SECRET: ${{ secrets.VAULT_CF_ACCESS_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v4

      - name: 🏗 Install Python dependencies
        run: pip install requests python-dotenv pyyaml

      - name: 📜 Prepare Origin CA
        run: |
          mkdir -p /tmp
          echo "${{ secrets.VAULT_ORIGIN_CA_PEM }}" > /tmp/origin_ca.pem

      - name: 🔐 Upload Vault Policies
        run: python3 docker/vault/scripts/create_policies.py

      - name: 🧬 Upload AppRoles & Generate env.generated
        run: python3 docker/vault/scripts/create_approles.py

      - name: 🔁 Sync to GitHub Secrets
        uses: gliech/create-github-secret-action@v1
        with:
          secrets: |
            $(awk -F= '{ printf "%s: %s\n", $1, $2 }' docker/vault/scripts/env.generated)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
